//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.SqlData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LOTERIA_GGEntities : DbContext
    {
        public LOTERIA_GGEntities()
            : base("name=LOTERIA_GGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public DbSet<NUB_SORTEO_USUARIO> NUB_SORTEO_USUARIO { get; set; }
        public DbSet<TBL_SORTEO> TBL_SORTEO { get; set; }
        public DbSet<TBL_USUARIO> TBL_USUARIO { get; set; }
    }
}
