//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.SqlData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BITACORA_ERROR
    {
        public int BITERR_ID { get; set; }
        public string BITERR_MSG { get; set; }
        public string BITERR_INNER_MSG { get; set; }
        public Nullable<long> USU_ID { get; set; }
        public System.DateTime BITERR_FECHA { get; set; }
    
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
    }
}
