//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.SqlData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MAILS
    {
        public int MAIL_ID { get; set; }
        public string MAIL_HTML { get; set; }
        public string MAIL_FROM { get; set; }
        public Nullable<System.DateTime> MAIL_FECHA { get; set; }
        public bool MAIL_VALIDADO { get; set; }
        public string MAIL_SUBJECT { get; set; }
        public string MAIL_CODIGO_TRANSFERENCIA { get; set; }
        public Nullable<int> MAIL_VISTO_POR { get; set; }
        public Nullable<System.DateTime> MAIL_FECHA_VISTO { get; set; }
        public Nullable<System.DateTime> MAIL_MODIFICADO { get; set; }
        public Nullable<int> MAIL_MODIFICADO_POR { get; set; }
        public Nullable<int> MAIL_USUARIO { get; set; }
        public Nullable<int> MAIL_MONTO { get; set; }
    }
}
