//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.SqlData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SORTEO_GRATIS
    {
        public long SG_ID { get; set; }
        public System.Guid SG_CODIGO { get; set; }
        public bool SG_VALIDO { get; set; }
        public Nullable<long> USU_ID { get; set; }
    }
}
