//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.SqlData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SORTEO
    {
        public TBL_SORTEO()
        {
            this.NUB_SORTEO_USUARIO = new HashSet<NUB_SORTEO_USUARIO>();
        }
    
        public long SOR_ID { get; set; }
        public bool SOR_LLENO { get; set; }
    
        public virtual ICollection<NUB_SORTEO_USUARIO> NUB_SORTEO_USUARIO { get; set; }
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
    }
}
